language: ruby
rvm:
  - 1.9.3
  - 2.1.0
  - 2.1.1
branches:
  only:
    - develop
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
bundler_args: --without production
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - CODECLIMATE_REPO_TOKEN=c4a73e487b5b8297808728964448353cf9169ac60b182c9c308326a40e20580d bundle exec rake
before_script:
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database rubyfatt_test'
  - psql -c 'create database rubyfatt_test' -U postgres
