development:
  adapter: mysql2
  database: rubyfatt_development
  host: localhost
  port: 3306
  username: root
  password:

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: rubyfatt_production
  host: localhost
  port: 3306
  username: root
  password:
