development:
  adapter: mysql2
  database: rubyfatt_development
  host: localhost
  port: 3306
  username: root
  password:

test:
  adapter: sqlite3
  encoding: utf8
  pool: 5
  timeout: 5000
  database: ":memory:"
  verbosity: quiet

production:
  adapter: mysql2
  database: rubyfatt_production
  host: localhost
  port: 3306
  username: root
  password:
